# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c195aa021197c48ee497ff270a6148a50cde2bcfc3caffd8edf827ca2e3eb1aeb0ca58812cee2e6b80abac2e2b3d9c94e4adc2be0262fd5806450edf62fa2f5

test:
  secret_key_base: 25c3965e6687d45283346c71e8d7ed22138d77ca464aadebc2d2d8ea0e53bc96629749a5973f8af49465a5d86ffc4b45c6d93e3315509b2070ddec8227b98691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
